symlink only directories when linking provider source files
hashicorp/terraform-plugin-test pull request #19
Opened 2020-03-23 11:16 UTC by kmoe

Symlinking every source file recursively leads to a huge number of file descriptors being allocated in large provider parallel test runs.

This PR modifies the test setup functionality so only directories are linked, non-recursively. 

This change assumes that acceptance tests do not use test fixture files residing adjacent to package source files - they should be in a separate directory, e.g. `./aws/test-fixtures/fixture.txt`, not `./aws/fixture.txt`. This assumption seems to be true for all the providers I've checked.

2020-03-24 14:57 UTC, appilon requested changes
nitpicky error checking

2020-03-24 14:57 UTC, appilon commented on util.go
> +	directory, _ := os.Open(srcDir)
check error, because you never know.

2020-03-24 14:57 UTC, appilon commented on util.go
> +	objects, err := directory.Readdir(-1)
check error

2020-04-20 13:56 UTC, kmoe commented
@appilon Don't review this yet, I'm testing out another idea by Paul...

2020-04-21 15:41 UTC, kmoe commented
Having tested out another solution suggested by @paultyng, I'm satisfied that it would work (with some refactoring), but it has the unfortunate consequence of requiring files to be written to the original provider source directory, so on balance I believe the solution in the present PR to be preferable.

### This PR

Each temporary working directory created will resemble the following:

```
baseDir
├── configDir
│   └── test.tf
├── src1 -> .../terraform-provider-random/random/src1
│   └── fixture.txt
├── src2 -> .../terraform-provider-random/random/src2
└── terraform-provider-random -> /tmp/go-test/.../terraform-provider-random
└── terraform.tfstate
```

Here, `baseDir` is used as the Terraform CLI working directory. `src1`, `src2`, and `terraform-provider-random` are symlinks. The directories `src1` and `src2` are sibling directories of the file under test, which is located in `terraform-provider-random/random`.

### Alternative solution

Paul suggested that instead of creating one symlink for each each sibling directory, a single symlink should be created for the package directory (`random/`). Terraform could then be initialised inside this directory. With appropriate arguments, Terraform CLI can operate with the config and state files located outside the working directory.

```
baseDir
├── configDir
│   ├── test.tf
│   └── terraform.tfstate
└── srcDir -> .../terraform-provider-random/random
    ├── src1
    │   └── fixture.txt
    ├── src2
    └── terraform-provider-random -> /tmp/go-test/.../terraform-provider-random
```

However, for reasons discussed in #11, the provider binary itself must be located in the Terraform working directory. This means that we must create the symlink for `terraform-provider-random` inside `srcDir`, _after following the symlink_, i.e. inside the actual provider source code directory on the filesystem.

While this isn't an insurmountable problem (providers could add it to `.gitignore`), it creates extra complexity in both adoption and implementation of the binary test driver: tests running in parallel would try to create this symlink multiple times as there is no way to know whether the symlink has been created by the current parallel test run or left behind from an earlier one.

### Conclusion

I believe the solution in the present PR is simple and good enough for now. It's likely we will have to change the way primary and auxiliary provider binaries are loaded due to the provider source changes in Terraform 0.13 anyway, which is out of scope for this PR.

2020-04-21 23:26 UTC, appilon approved these changes

2020-04-22 13:43 UTC, merged