Propagate reattach info
hashicorp/terraform-plugin-test pull request #38
Opened 2020-09-07 21:00 UTC by kmoe

2020-09-08 20:13 UTC, paddycarver requested changes
Called out some errors that need checked (sorry for the repetition).

We could also automate this with https://github.com/kisielk/errcheck or golangci-lint.

2020-09-08 20:13 UTC, paddycarver commented on working_dir.go
> +	tf.SetEnv(wd.buildEnv())
There's an error here we're not checking.

2020-09-08 20:13 UTC, paddycarver commented on working_dir.go
> +	wd.tf.SetEnv(wd.buildEnv())
Error here should be checked.

2020-09-08 20:13 UTC, paddycarver commented on working_dir.go
> +	wd.tf.SetEnv(wd.buildEnv())
Error here should be checked.

2020-09-08 20:13 UTC, paddycarver commented on working_dir.go
> +	wd.tf.SetEnv(wd.buildEnv())
Error here should be checked

2020-09-08 20:13 UTC, paddycarver commented on working_dir.go
> +	wd.tf.SetEnv(wd.buildEnv())
Error here should be checked.

2020-09-08 20:13 UTC, paddycarver commented on working_dir.go
> +	wd.tf.SetEnv(wd.buildEnv())
Error here should be checked.

2020-09-08 20:13 UTC, paddycarver commented on working_dir.go
> +	wd.tf.SetEnv(wd.buildEnv())
Error here should be checked.

2020-09-08 20:13 UTC, paddycarver commented on working_dir.go
> +	wd.tf.SetEnv(wd.buildEnv())
Error here should be checked.

2020-09-08 20:13 UTC, paddycarver commented on working_dir.go
> +	wd.tf.SetEnv(wd.buildEnv())
Error here should be checked.

2020-09-08 20:13 UTC, paddycarver commented on working_dir.go
> +	wd.tf.SetEnv(wd.buildEnv())
Error here should be checked.

2020-09-08 20:13 UTC, paddycarver commented on working_dir.go
> +	wd.tf.SetEnv(wd.buildEnv())
Error here should be checked.

2020-09-08 20:13 UTC, paddycarver commented on working_dir.go
> +	wd.tf.SetEnv(wd.buildEnv())
Error here should be checked.

2020-09-09 18:03 UTC, kmoe commented
After some discussion, I'm removing the propagation of the whole `os.Environ()` into the tfexec environment, because it causes unexpected results with reattach tests. Leaving the two (now a little counterintuitive, and in any case unused) `wd.Setenv()` and `wd.Unsetenv()`, which will be removed when tftest is very shortly moved into the SDK itself.

2020-09-09 19:54 UTC, paddycarver approved these changes

2020-09-09 20:22 UTC, merged